import type { Opportunity } from "./types.ts";
import { CANONICAL_OPPORTUNITY_COUNT } from "./types.ts";

/**
 * Canonical V9 Opportunity DB (25 rows), mapped into `Opportunity`.
 * IDs `V9-01` … `V9-25` are internal row-order identifiers only.
 *
 * Unused V9 source columns (not stored — matching has no field for them):
 * Category, Maximum Recommended Startup Budget, Ideal Time Required,
 * Skill Fit Level, Risk Level, Income Potential Score, and the duplicate
 * Hard Constraint Budget/Time/Risk columns (same values as the mapped mins).
 */
export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "V9-01",
    name: "Freelance Writing",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: ["Create portfolio", "Pitch 10 clients", "Secure first gig"],
    actions: ["Set up Upwork", "Write 3 samples", "Send cold emails"],
  },
  {
    id: "V9-02",
    name: "Dropshipping",
    minBudgetDollars: 500,
    minTimeHours: 10,
    skills: ["Sales, Marketing, or Customer Service"],
    techRequirement: 4,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 4,
    incomePotentialMin: 2500,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Find niche", "Build Shopify store", "Launch first ad"],
    actions: ["Research products", "Design logo", "Set up Facebook Ads"],
  },
  {
    id: "V9-03",
    name: "Virtual Assistant",
    minBudgetDollars: 0,
    minTimeHours: 10,
    skills: ["Administrative and Organizational"],
    techRequirement: 3,
    workingStyles: ["I prefer ongoing, repetitive tasks"],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: ["Define services", "Create profile", "Get first client"],
    actions: ["List skills", "Join VA groups", "Apply to 5 jobs"],
  },
  {
    id: "V9-04",
    name: "Dividend Investing",
    minBudgetDollars: 2000,
    minTimeHours: 2,
    skills: ["Data Analysis"],
    techRequirement: 2,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 3,
    incomePotentialMin: 250,
    incomePotentialMax: 500,
    goals: ["Build a savings buffer or emergency fund"],
    milestones: ["Open brokerage", "Research ETFs", "Make first trade"],
    actions: ["Fund account", "Pick 3 stocks", "Set up DRIP"],
  },
  {
    id: "V9-05",
    name: "Uber Driving",
    minBudgetDollars: 100,
    minTimeHours: 10,
    skills: ["Manual Labor or Physical Services"],
    techRequirement: 1,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 2,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Pay off specific debt"],
    milestones: ["Vehicle inspection", "Background check", "First ride"],
    actions: ["Clean car", "Download app", "Set schedule"],
  },
  {
    id: "V9-06",
    name: "YouTube Channel",
    minBudgetDollars: 100,
    minTimeHours: 10,
    skills: ["Design and Creative Arts"],
    techRequirement: 4,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 3,
    incomePotentialMin: 5000,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Pick niche", "Upload 10 videos", "Get monetized"],
    actions: ["Buy mic", "Script first video", "Learn Premiere Pro"],
  },
  {
    id: "V9-07",
    name: "Social Media Management",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Sales, Marketing, or Customer Service"],
    techRequirement: 3,
    workingStyles: ["I prefer ongoing, repetitive tasks"],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: ["Create own profiles", "Pitch local biz", "Get first client"],
    actions: ["Build portfolio", "Set up Hootsuite", "Send DMs"],
  },
  {
    id: "V9-08",
    name: "Graphic Design",
    minBudgetDollars: 50,
    minTimeHours: 5,
    skills: ["Design and Creative Arts"],
    techRequirement: 4,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: ["Get Adobe CC", "Build portfolio", "Land first client"],
    actions: ["Learn Illustrator", "Make mockups", "Join Fiverr"],
  },
  {
    id: "V9-09",
    name: "Affiliate Marketing",
    minBudgetDollars: 100,
    minTimeHours: 10,
    skills: ["Sales, Marketing, or Customer Service"],
    techRequirement: 3,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 2,
    incomePotentialMin: 2500,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Pick niche", "Build blog", "Get first sale"],
    actions: ["Buy domain", "Write 5 posts", "Join Amazon Assoc"],
  },
  {
    id: "V9-10",
    name: "Online Tutoring",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Teaching or Consulting"],
    techRequirement: 2,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 1,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: ["Pick subject", "Make profile", "Teach first class"],
    actions: ["Test webcam", "Join VIPKid", "Prepare lesson"],
  },
  {
    id: "V9-11",
    name: "Web Development",
    minBudgetDollars: 0,
    minTimeHours: 10,
    skills: ["Technical/Coding/IT"],
    techRequirement: 5,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 2500,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Learn HTML/CSS", "Build 3 sites", "Land first client"],
    actions: ["Take Udemy course", "Setup GitHub", "Pitch on Upwork"],
  },
  {
    id: "V9-12",
    name: "Data Entry",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Administrative and Organizational"],
    techRequirement: 2,
    workingStyles: ["I prefer ongoing, repetitive tasks"],
    riskRequirement: 1,
    incomePotentialMin: 250,
    incomePotentialMax: 500,
    goals: ["Build a savings buffer or emergency fund"],
    milestones: ["Update resume", "Apply on Upwork", "Complete first job"],
    actions: ["Learn Excel", "Take typing test", "Search jobs"],
  },
  {
    id: "V9-13",
    name: "Print on Demand",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Design and Creative Arts"],
    techRequirement: 3,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 2,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: ["Pick niche", "Create 10 designs", "Make first sale"],
    actions: ["Open Printify", "Design on Canva", "List on Etsy"],
  },
  {
    id: "V9-14",
    name: "Dog Walking",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Manual Labor or Physical Services"],
    techRequirement: 1,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 1,
    incomePotentialMin: 250,
    incomePotentialMax: 500,
    goals: ["Pay off specific debt"],
    milestones: ["Create Rover profile", "Pass background", "First walk"],
    actions: ["Buy dog bags", "Set availability", "Share on Facebook"],
  },
  {
    id: "V9-15",
    name: "Copywriting",
    minBudgetDollars: 0,
    minTimeHours: 5,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Read copywriting book",
      "Write 3 spec pieces",
      "Land first client",
    ],
    actions: ["Learn AIDA", "Build portfolio", "Send cold emails"],
  },
  {
    id: "V9-16",
    name: "App Development",
    minBudgetDollars: 100,
    minTimeHours: 15,
    skills: ["Technical/Coding/IT"],
    techRequirement: 5,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 4,
    incomePotentialMin: 5000,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Learn Swift/Kotlin", "Build MVP", "Launch on App Store"],
    actions: ["Take course", "Design UI", "Setup Developer Acct"],
  },
  {
    id: "V9-17",
    name: "Photography",
    minBudgetDollars: 500,
    minTimeHours: 5,
    skills: ["Design and Creative Arts"],
    techRequirement: 3,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 2,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Fund a specific investment or purchase"],
    milestones: ["Buy camera", "Shoot 3 free gigs", "Book paid shoot"],
    actions: ["Learn Lightroom", "Make portfolio", "Post on IG"],
  },
  {
    id: "V9-18",
    name: "SEO Consulting",
    minBudgetDollars: 0,
    minTimeHours: 10,
    skills: ["Data Analysis"],
    techRequirement: 4,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 2,
    incomePotentialMin: 2500,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Learn SEO basics", "Rank own site", "Land first client"],
    actions: ["Take Ahrefs course", "Do site audit", "Pitch local biz"],
  },
  {
    id: "V9-19",
    name: "Online Course Creation",
    minBudgetDollars: 100,
    minTimeHours: 10,
    skills: ["Teaching or Consulting"],
    techRequirement: 3,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 3,
    incomePotentialMin: 2500,
    incomePotentialMax: 5000,
    goals: ["Replace my full-time salary"],
    milestones: ["Outline course", "Record videos", "Launch course"],
    actions: ["Pick topic", "Buy mic", "Setup Teachable"],
  },
  {
    id: "V9-20",
    name: "IT Support",
    minBudgetDollars: 0,
    minTimeHours: 10,
    skills: ["Technical/Coding/IT"],
    techRequirement: 4,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: ["Define services", "Setup Helpdesk", "Get first client"],
    actions: ["Update resume", "Join Upwork", "Apply to jobs"],
  },
  {
    id: "V9-21",
    name: "Proofreading & Editing",
    minBudgetDollars: 0,
    minTimeHours: 2,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Choose a niche",
      "Edit 3 sample pieces",
      "Land first client",
    ],
    actions: [
      "Create before/after samples",
      "Build a simple portfolio",
      "Pitch writers and businesses",
    ],
  },
  {
    id: "V9-22",
    name: "Resume & LinkedIn Profile Writing",
    minBudgetDollars: 0,
    minTimeHours: 2,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Create 2 sample profiles",
      "Offer first 3 clients a launch rate",
      "Get first testimonial",
    ],
    actions: [
      "Build sample portfolio",
      "Create intake questionnaire",
      "Contact job seekers and professionals",
    ],
  },
  {
    id: "V9-23",
    name: "Small Business Email Copy",
    minBudgetDollars: 0,
    minTimeHours: 2,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: [
      "I prefer interacting with people (in person or online)",
    ],
    riskRequirement: 1,
    incomePotentialMin: 1000,
    incomePotentialMax: 2500,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Write 3 sample emails",
      "Offer a starter package",
      "Land first client",
    ],
    actions: [
      "Learn basic email copy",
      "Build a sample pack",
      "Contact local businesses",
    ],
  },
  {
    id: "V9-24",
    name: "Marketplace Listing Writer",
    minBudgetDollars: 0,
    minTimeHours: 2,
    skills: ["Writing and Content Creation"],
    techRequirement: 2,
    workingStyles: ["I prefer project-based work with deadlines"],
    riskRequirement: 1,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Write 5 sample listings",
      "Create a service offer",
      "Land first client",
    ],
    actions: [
      "Study strong listings",
      "Create listing templates",
      "Pitch marketplace sellers",
    ],
  },
  {
    id: "V9-25",
    name: "Content Repurposing Writer",
    minBudgetDollars: 0,
    minTimeHours: 3,
    skills: ["Writing and Content Creation"],
    techRequirement: 3,
    workingStyles: ["I prefer working alone remotely"],
    riskRequirement: 1,
    incomePotentialMin: 500,
    incomePotentialMax: 1000,
    goals: ["Generate a secondary side income"],
    milestones: [
      "Create 3 repurposing samples",
      "Build a simple offer",
      "Land first client",
    ],
    actions: [
      "Turn one article into 5 posts",
      "Create a portfolio page",
      "Pitch creators and small businesses",
    ],
  },
];

export const SMALL_BUSINESS_EMAIL_COPY_DISPLAY = {
  name: "Small Business Email Copy",
  milestones: [
    "Write 3 sample emails",
    "Offer a starter package",
    "Land first client",
  ],
  actions: [
    "Learn basic email copy",
    "Build a sample pack",
    "Contact local businesses",
  ],
} as const;

export function isCanonicalCatalogLoaded(): boolean {
  return OPPORTUNITIES.length === CANONICAL_OPPORTUNITY_COUNT;
}
